### ISSUE TITLE
rc function and portraits

### ISSUE THREAD

**Issue by DarkTl** [Xela00/PyTFall#37]
So when we use lines ike char.say "...", there is actually character's portrait next to the text.
But when we use lines like $ rc("...", "..."), there is no portrait. That should be fixed.

**Comment by Xela00** [comment]
= Link chr.say to function call instead of chr.

**Comment by DarkTl** [comment]
I don't get it, are you proposing me to do something, or it's just a note for yourself? Because if the former, you should clarify it :smile:

**Comment by Xela00** [comment]
It's a note :)
