### ISSUE TITLE
An option to give gold

### ISSUE THREAD

**Issue by DarkTl** [Xela00/PyTFall#45]
...to a slave. Or take it. Freely. Because
- We assume that they trained perfectly, thus you can trust them.
- We assume that they indistinguishable from free citizens to avoid showing how many slaves exist. Thus they might as well visit a shop, having such a permission and money.
- Unlike free characters, they, being a property, cannot have a property. Thus an option to freely give or take their gold, just like you already can do with items, makes sense, and even without any disposition changes.

**Comment by Xela00** [comment]
This is basic stuff for interactions, I'll just assign it to you :8ball:

**Comment by DarkTl** [comment]
Actually, I mean arbitrary amount. That means either a bar or a field for entering digits. And I don't think renpy is good with entering fields.

**Comment by Xela00** [comment]
http://www.renpy.org/doc/html/input.html

$ temp = renpy.input("Enter a Numer:", allow="1234567890")

**Comment by DarkTl** [comment]
It's more or less true, except the fact that input returns unicode string, not integer. 
I also was quite surprised by the fact that you cannot do char.gold >= int(temp).
Instead you have to 
    $ python_BS = int(temp)
    if char.gold >= python_BS:
