### ISSUE TITLE
Interactions

### ISSUE THREAD

**Issue by DarkTl** [Xela00/PyTFall#5]
I need two things for interactions. First are those lists for friends and lovers. Second is an option to pick a partner for les from characters, check for BOTH characters disposition (in the future lovers list too), traits (non-lesbian might not agree) and skills and show their pics together next to each other with some text.

**Comment by Xela00** [comment]
Ok, I'll get right on that :)

**Comment by Xela00** [comment]
Possible solution to Lesbo issue: http://www.pinkpetal.org/index.php?topic=1291.msg35530#msg35530
